### ISSUE TITLE
[frontend][landing] Add new sections to the landing page

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid-landing-page#39]
We need to design and implement new sections to the landing page:
- A section about how we deal with security and privacy. The copy is to be written by @skyhorse
- A section about why we are doing this / mission.
  - it should include our mission statement (see below)

- Contribute to reduce the impact of COVID-19
   1. Saving lives
   2. Reduce the economical impact
   3. Protect our way of living

**Comment by pfortuna** [comment]
Let's add a third section called "Quem somos"

The marketing team has already this content ("Quem somos").

**Comment by geiras** [comment]
@pfortuna, can you provide a link to where is that exact content for the Landing Page section "Quem somos"?

Also, Orlando already worked on the other two sections and this is the design we have so far:
![image](https://user-images.githubusercontent.com/22840903/77837100-b5d44380-7154-11ea-9a41-a14a7cd96677.png)

**Comment by pfortuna** [comment]
We are still waiting for the copy. Hang in there folks!

**Comment by tiruicosta** [comment]
We are going with two sections, but we still need copy! 

Current drafts:
- Quem somos: https://docs.google.com/document/d/1z_2twVSxCR1vhaG54ObateXSKtE2ZU0DzotkGT1Im80/edit
- Privacidade: https://docs.google.com/document/d/1LZwsr_WBHBpkHMmbLO1veMtDjf0oL8lo13HzWH3u_X0/edit#heading=h.sh20mp8uywtw

**Comment by pfortuna** [comment]
Copy please!!

**Comment by CarmenSantosLima** [comment]
@pfortuna and @geiras, now yes notified! I will follow up on these issues ;-)
