### ISSUE TITLE
[frontend][landing] Create a "Quem somos" page

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid-landing-page#46]
Create a Quem somos page according to the structure on the Google Drive documents:
- QuemSomos_LandingPage
- CovidografiaCodigoDeConduta

**Comment by pfortuna** [comment]
This page will not have the codigo de conduta. That will be a separate page.

Design here:
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3974%3A6550

**Comment by geiras** [comment]
The final copy and the hyperlinks can be found on this document: https://docs.google.com/document/d/1z_2twVSxCR1vhaG54ObateXSKtE2ZU0DzotkGT1Im80/edit?usp=sharing
