### ISSUE TITLE
[frontend][landing] Create a "Privacidade" page

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid-landing-page#48]
Create this page with the copy from the google doc:
Covidografia-PrivacidadeDados

**Comment by orlandosrocha** [comment]
Updated page at: 
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=864%3A2574

**Comment by geiras** [comment]
![image](https://user-images.githubusercontent.com/22840903/78510167-49c49180-778b-11ea-8a97-77195115a4b0.png)

**Comment by geiras** [comment]
Final copy and hyperlinks can be found on this document:
https://docs.google.com/document/d/1LZwsr_WBHBpkHMmbLO1veMtDjf0oL8lo13HzWH3u_X0/edit?usp=sharing
