### ISSUE TITLE
[frontend][landing] Create a "código de conduta" specific page

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid-landing-page#50]
Previously this was under the "quem somos" page. But we decided to promote this to its own page.

**Comment by geiras** [comment]
![image](https://user-images.githubusercontent.com/22840903/78510880-4f70a600-7790-11ea-8fc5-c3e872bcedca.png)
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=4007%3A7141

The page still needs a copy review to make sure everything was copied correctly from the documents provided. 

The page follows the same structure as Privacy page, you may want to copy the same components.

**Comment by geiras** [comment]
The final copy and hyperlinks can be found on this file:
https://docs.google.com/document/d/1H_4CQiPrrXPhoZBupZNxkSxnJBjgd1C64kkx64h_VO4/edit?usp=sharing
