### ISSUE TITLE
[frontend][landing] Copy corrections in landing page

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid-landing-page#71]
change names
Nelson (sem acento) Patrício – Digital Influencer
Margarida da Silva - Digital Influencer

**Comment by pfortuna** [comment]
@lcfb91 are those changes in the "Quem somos" page?

I'm also including in this page, 2 additions to the developer team in the "quem somos" pages.

<img width="710" alt="Screenshot 2020-04-07 at 18 49 05" src="https://user-images.githubusercontent.com/5217265/78702480-8fef3180-7900-11ea-949e-c06e8bf93e4a.png">

**Comment by geiras** [comment]
Figma file updated with the requested changes.
